apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.canvasPort }}
      targetPort: canvas
      protocol: TCP
      name: canvas
    - port: {{ .Values.service.eventsAPIPort }}
      targetPort: eventsapi
      protocol: TCP
      name: eventsapi
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
